# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
# color
color:
  primary: '#0078E7'
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00C4B6"
#   button_hover: "#FF7242"
#   text_selection: "#00C4B6"
#   link_color: "#858585"
#   hr_color: "#A4D8FA"
  tag_start_color: "#A4D8FA"
  tag_end_color: "#1B9EF3"

# main menu navigation
menu:
  home:
    path: /
    icon: fas fa-home
  archives:
    path: /archives
    icon: fas fa-archive
  tags:
    path: /tags
    icon: fas fa-tags
  categories:
    path: /categories
    icon: fas fa-folder
  about:
    path: /about
    icon: fas fa-info

# stylesheets loaded in the <head>
stylesheets:
- /css/hexo-theme-starry.css

# scripts loaded in the end of the body
scripts:
- /js/hexo-theme-starry.js
- /js/utils.js
- /js/starry-boot.js
- /js/ui/fireworks.js
- /js/component/sidebar.js

# starry

# cdn for third-party library
cdn:
  css:
    # font
    font: https://fonts.googleapis.com/css?family=Montserrat
    # icon
    fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.8.1/css/all.min.css
    # ionicons: https://cdn.jsdelivr.net/npm/ionicons@4.5.6/dist/css/ionicons.min.css
    # material-design-icons: https://fonts.googleapis.com/icon?family=Material+Icons
    # iconfont: //at.alicdn.com/t/font_xxxxxxxxxx.css
    # markdown
    # star-markdown-css: https://unpkg.com/star-markdown-css@0.0.3/dist/star/star-common.min.css
    # blood-markdown-css: https://unpkg.com/star-markdown-css@0.0.3/dist/blood/blood-common.min.css
  js:
    # icon
    # ionicons: https://cdn.jsdelivr.net/npm/ionicons@4.5.6/dist/ionicons.js
    # ui
    anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    # fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js
    # velocity-ui: https://cdn.jsdelivr.net/npm/velocity-ui-pack@latest/velocity.ui.min.js

# Article

# Footer Settings
# ---------------
footer:
  since: 2018

  # Icon between year and copyright info.
  icon:
    # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons/
    # `heart` is recommended with animation in red (#ff0000).
    name: cloud
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: '#0078E7'

  powered:
    # Hexo link (Powered by Hexo).
    enable: true
    # Version info of Hexo after Hexo link (vX.X.X).
    version: true
  
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # http://www.beian.miit.gov.cn
  beian:
    enable: false
    # icp: 苏ICP备xxxxxxxx号
  
  # Any custom text can be defined here.
  # custom_text: Hosted by <a href="https://pages.coding.me" class="theme-link" rel="noopener" target="_blank">Coding Pages</a>

# Show Views / Visitors of the website / page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi
busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: far fa-user
  site_pv: true
  site_pv_icon: far fa-eye
  page_pv: true
  page_pv_icon: far fa-eye

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

# Post wordcount display settings
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  item_text_post: true
  item_text_total: true
  awl: 2
  wpm: 250