# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
# color
color:
  primary: '#0078E7'
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00C4B6"
#   button_hover: "#FF7242"
#   text_selection: "#00C4B6"
#   link_color: "#858585"
#   hr_color: "#A4D8FA"
  tag_start_color: "#A4D8FA"
  tag_end_color: "#1B9EF3"

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

# Posts / Categories / Tags in sidebar.
site_state: true

# Set rss to false to disable feed link.
# Leave rss as blank to use site's feed link, and install hexo-generator-feed: `npm install hexo-generator-feed --save`.
# Set rss to specific value if you have burned your feed already.
rss:

# Social Links.
social:
  GitHub: 
    link: https://github.com/YunYouJun
    icon: fab fa-github
    color: black
  E-Mail:
    link: mailto:me@yunyoujun.cn
    icon: far fa-envelope
  微博:
    link: https://weibo.com/jizhideyunyoujun
    icon: fab fa-weibo
    color: red
  豆瓣:
    link: https://www.douban.com/people/yunyoujun/
    icon: iconfont icon-douban
    color: green
  网易云音乐:
    link: https://music.163.com/#/user/home?id=247102977
    icon: iconfont icon-netease-cloud-music
    color: red
  知乎:
    link: https://www.zhihu.com/people/yunyoujun/
    icon: iconfont icon-zhihu
    color: blue
  哔哩哔哩动画:
    link: https://space.bilibili.com/1579790
    icon: iconfont icon-bilibili
    color: '#f25a8d'
  # bangumi: http://bangumi.tv/user/yunyoujun || television
  # pixiv: https://pixiv.me/yunyoujun || paint-brush
  # Google: https://plus.google.com/yourname || google
  # Twitter: https://twitter.com/yunyoujun || twitter
  # FB Page: https://www.facebook.com/yourname || facebook
  # StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  # YouTube: https://youtube.com/yourname || youtube
  # Instagram: https://instagram.com/yourname || instagram
  # Skype: skype:yourname?call|chat || skype

# Sidebar Avatar
avatar:
  url: /images/avatar.jpg
  # If true, the avatar would be dispalyed in circle.
  rounded: false
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1

# main menu navigation
menu:
  home:
    path: /
    icon: fas fa-home
  archives:
    path: /archives
    icon: fas fa-archive
  tags:
    path: /tags
    icon: fas fa-tags
  categories:
    path: /categories
    icon: fas fa-folder
  about:
    path: /about
    icon: fas fa-info

# stylesheets loaded in the <head>
stylesheets:
- /css/hexo-theme-starry.css

# scripts loaded in the end of the body
scripts:
- /js/hexo-theme-starry.js
- /js/utils.js
- /js/starry-boot.js
- /js/component/sidebar.js
- /js/ui/fireworks.js

# starry

# cdn for third-party library (always include)
cdn:
  css:
    # font
    font: https://fonts.googleapis.com/css?family=Montserrat
    # font: https://fonts.loli.net/css?family=Montserrat
    # icon
    fontawesome: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.8.1/css/all.min.css
    # ionicons: https://cdn.jsdelivr.net/npm/ionicons@4.5.6/dist/css/ionicons.min.css
    iconfont: //at.alicdn.com/t/font_1140697_rowhas0mn3c.css
    material-design-icons: https://fonts.googleapis.com/icon?family=Material+Icons
    # markdown
    # github-markdown-css: https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/3.0.1/github-markdown.min.css
    # star-markdown-css: https://unpkg.com/star-markdown-css@0.0.3/dist/star/star-common.min.css
    # star-markdown-css: https://cdn.jsdelivr.net/npm/star-markdown-css@0.0.3/dist/star/star-markdown.min.css
    # blood-markdown-css: https://unpkg.com/star-markdown-css@0.0.3/dist/blood/blood-common.min.css
    # material
    # material-design-lite: https://cdn.jsdelivr.net/npm/material-design-lite/material.min.css
    fancybox: //cdn.jsdelivr.net/npm/@fancyapps/fancybox/dist/jquery.fancybox.min.css
  js:
    # icon
    # ionicons: https://cdn.jsdelivr.net/npm/ionicons@4.5.6/dist/ionicons.js
    # ui
    anime: //cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
    jquery: //cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    # fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
    velocity: //cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js
    velocity-ui: //cdn.jsdelivr.net/npm/velocity-ui-pack@latest/velocity.ui.min.js
    # material-design-lite: https://cdn.jsdelivr.net/npm/material-design-lite/material.min.js
    fancybox: //cdn.jsdelivr.net/npm/@fancyapps/fancybox/dist/jquery.fancybox.min.js

# cdn for third-party library (alternative include)
vendors:
  gitalk_css: //cdn.jsdelivr.net/npm/gitalk/dist/gitalk.css
  gitalk_js: //cdn.jsdelivr.net/npm/gitalk/dist/gitalk.min.js
  algolia_instant_css: //cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.min.css
  algolia_instant_js: //cdn.jsdelivr.net/npm/instantsearch.js@2/dist/instantsearch.min.js
  leancloud_storage: //cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js
  valine_js: //cdn.jsdelivr.net/npm/valine/dist/Valine.min.js

# Article
# ---------------
# Code Highlight theme
# Available values: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

# Reward (Donate)
reward_settings:
  # If true, reward would be displayed in every article by default.
  # You can show or hide reward in a specific article throuth `reward: true | false` in Front Matter.
  enable: true
  #comment: Donate comment here
reward:
  wechatpay: /images/donate/wechatpay.png
  alipay: /images/donate/alipay.jpg

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/share-your-work/licensing-types-examples
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.fr, deed.de, etc.
creative_commons:
  license: by-nc-sa
  sidebar: false
  post: true
  language: deed.zh

# AddThis Share, See: https://www.addthis.com
# Go to https://www.addthis.com/dashboard to customize your tools.
# add_this_id:

# Comments
# -----------
# gitalk
# See: https://github.com/gitalk/gitalk
gitalk:
  enable: false
  clientID: # Github Application Client ID
  clientSecret: # Github Application Client Secret
  repo: # GitHub repo
  owner: # GitHub repo owner
  admin: # GitHub repo owner and collaborators, only these guys can initialize github issues

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: false
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# Footer Settings
# ---------------
footer:
  since: 2018

  # Icon between year and copyright info.
  icon:
    # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons/
    # `heart` is recommended with animation in red (#ff0000).
    name: cloud
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: '#0078E7'

  powered:
    # Hexo link (Powered by Hexo).
    enable: true
    # Version info of Hexo after Hexo link (vX.X.X).
    version: true
  
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # http://www.beian.miit.gov.cn
  beian:
    enable: false
    # icp: 苏ICP备xxxxxxxx号
  
  # Any custom text can be defined here.
  # custom_text: Hosted by <a href="https://pages.coding.me" class="theme-link" rel="noopener" target="_blank">Coding Pages</a>

# Show Views / Visitors of the website / page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi
busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: far fa-user
  site_pv: true
  site_pv_icon: far fa-eye
  page_pv: true
  page_pv_icon: far fa-eye

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

# Post wordcount display settings
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  item_text_post: true
  item_text_total: true
  awl: 2
  wpm: 250

# search
# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: false

algolia_search:
  enable: false
  hits:
    per_page: 10 # the number of search results per page

# Ads
# ---------------
# Google Adsense
google_adsense:
  enable: false
  client: ca-pub-xxxxxxxxxx
  enable_page_level_ads: true

# Analysis
# ---------------
google_analytics:
  enable: false
  id: UA-XXXXXXXXX-X